import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { MOM } from "./mom-types";

export function downloadMomPdf(mom: MOM) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;

  // Header band
  doc.setFillColor(30, 41, 59); // slate-800
  doc.rect(0, 0, pageWidth, 70, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Minutes of Meeting (MOM)", margin, 32);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Client Visit MOM Portal", margin, 52);

  doc.setTextColor(20, 20, 20);
  let y = 95;

  // Meeting Information block
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Meeting Information", margin, y);
  y += 6;
  doc.setDrawColor(220);
  doc.line(margin, y, pageWidth - margin, y);
  y += 12;

  autoTable(doc, {
    startY: y,
    theme: "plain",
    styles: { fontSize: 10, cellPadding: 3 },
    body: [
      ["Client / Institute", mom.client_name],
      ["Meeting Date", mom.meeting_date],
      ["Meeting Type", mom.meeting_type === "online" ? "Online" : "Offline"],
      ["Employee", mom.employee_name],
      ["Location", mom.location || "—"],
    ],
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 130, textColor: [80, 80, 80] },
    },
    margin: { left: margin, right: margin },
  });
  // @ts-expect-error autotable adds lastAutoTable
  y = doc.lastAutoTable.finalY + 18;

  const section = (title: string) => {
    if (y > 760) {
      doc.addPage();
      y = 60;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(30, 41, 59);
    doc.text(title, margin, y);
    doc.setTextColor(20, 20, 20);
    y += 6;
    doc.setDrawColor(220);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;
  };

  if (mom.attendees.length) {
    section("Attendees");
    autoTable(doc, {
      startY: y,
      head: [["Name", "Designation", "Mobile"]],
      body: mom.attendees.map((a) => [a.name, a.designation, a.mobile || "—"]),
      styles: { fontSize: 9, cellPadding: 4 },
      headStyles: { fillColor: [241, 245, 249], textColor: 30 },
      margin: { left: margin, right: margin },
    });
    // @ts-expect-error autotable
    y = doc.lastAutoTable.finalY + 14;
  }

  if (mom.discussion_points.length) {
    section("Discussion Points");
    autoTable(doc, {
      startY: y,
      head: [["Module", "Details"]],
      body: mom.discussion_points.map((d) => [d.module, d.details]),
      styles: { fontSize: 9, cellPadding: 4 },
      headStyles: { fillColor: [241, 245, 249], textColor: 30 },
      columnStyles: { 0: { cellWidth: 100 } },
      margin: { left: margin, right: margin },
    });
    // @ts-expect-error autotable
    y = doc.lastAutoTable.finalY + 14;
  }

  if (mom.work_completed.length) {
    section("Work Completed");
    autoTable(doc, {
      startY: y,
      head: [["Module", "Task Completed"]],
      body: mom.work_completed.map((w) => [w.module, w.task]),
      styles: { fontSize: 9, cellPadding: 4 },
      headStyles: { fillColor: [241, 245, 249], textColor: 30 },
      columnStyles: { 0: { cellWidth: 100 } },
      margin: { left: margin, right: margin },
    });
    // @ts-expect-error autotable
    y = doc.lastAutoTable.finalY + 14;
  }

  if (mom.pending_points.length) {
    section("Pending Requirements");
    autoTable(doc, {
      startY: y,
      head: [["Module", "Requirement", "Priority"]],
      body: mom.pending_points.map((p) => [p.module, p.requirement, p.priority]),
      styles: { fontSize: 9, cellPadding: 4 },
      headStyles: { fillColor: [241, 245, 249], textColor: 30 },
      columnStyles: { 0: { cellWidth: 100 }, 2: { cellWidth: 70 } },
      margin: { left: margin, right: margin },
    });
    // @ts-expect-error autotable
    y = doc.lastAutoTable.finalY + 14;
  }

  if (mom.summary) {
    section("Conclusion");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(mom.summary, pageWidth - margin * 2);
    if (y + lines.length * 13 > 780) {
      doc.addPage();
      y = 60;
    }
    doc.text(lines, margin, y);
    y += lines.length * 13;
  }

  // Footer on each page
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(120);
    doc.text(
      `Generated by Client Visit MOM Portal  •  Page ${i} of ${pages}`,
      pageWidth / 2,
      820,
      { align: "center" },
    );
  }

  const safe = mom.client_name.replace(/[^a-z0-9]+/gi, "_");
  doc.save(`MOM_${safe}_${mom.meeting_date}.pdf`);
}
