/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MomNewRouteImport } from './routes/mom.new'
import { Route as MomIdRouteImport } from './routes/mom.$id'
import { Route as EditIdRouteImport } from './routes/edit.$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MomNewRoute = MomNewRouteImport.update({
  id: '/mom/new',
  path: '/mom/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MomIdRoute = MomIdRouteImport.update({
  id: '/mom/$id',
  path: '/mom/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditIdRoute = EditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/edit/$id': typeof EditIdRoute
  '/mom/$id': typeof MomIdRoute
  '/mom/new': typeof MomNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/edit/$id': typeof EditIdRoute
  '/mom/$id': typeof MomIdRoute
  '/mom/new': typeof MomNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/edit/$id': typeof EditIdRoute
  '/mom/$id': typeof MomIdRoute
  '/mom/new': typeof MomNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/edit/$id' | '/mom/$id' | '/mom/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/edit/$id' | '/mom/$id' | '/mom/new'
  id: '__root__' | '/' | '/dashboard' | '/edit/$id' | '/mom/$id' | '/mom/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EditIdRoute: typeof EditIdRoute
  MomIdRoute: typeof MomIdRoute
  MomNewRoute: typeof MomNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mom/new': {
      id: '/mom/new'
      path: '/mom/new'
      fullPath: '/mom/new'
      preLoaderRoute: typeof MomNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mom/$id': {
      id: '/mom/$id'
      path: '/mom/$id'
      fullPath: '/mom/$id'
      preLoaderRoute: typeof MomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$id': {
      id: '/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof EditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EditIdRoute: EditIdRoute,
  MomIdRoute: MomIdRoute,
  MomNewRoute: MomNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
