/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as EditIdRouteImport } from './routes/edit.$id'
import { Route as MomIdRouteImport } from './routes/mom.$id'
import { Route as MomNewRouteImport } from './routes/mom.new'
import { Route as ApiPublicMomsRouteImport } from './routes/api/public/moms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const EditIdRoute = EditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MomIdRoute = MomIdRouteImport.update({
  id: '/mom/$id',
  path: '/mom/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MomNewRoute = MomNewRouteImport.update({
  id: '/mom/new',
  path: '/mom/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMomsRoute = ApiPublicMomsRouteImport.update({
  id: '/api/public/moms',
  path: '/api/public/moms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meetings': typeof MeetingsRoute
  '/edit/$id': typeof EditIdRoute
  '/mom/$id': typeof MomIdRoute
  '/mom/new': typeof MomNewRoute
  '/api/public/moms': typeof ApiPublicMomsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meetings': typeof MeetingsRoute
  '/edit/$id': typeof EditIdRoute
  '/mom/$id': typeof MomIdRoute
  '/mom/new': typeof MomNewRoute
  '/api/public/moms': typeof ApiPublicMomsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meetings': typeof MeetingsRoute
  '/edit/$id': typeof EditIdRoute
  '/mom/$id': typeof MomIdRoute
  '/mom/new': typeof MomNewRoute
  '/api/public/moms': typeof ApiPublicMomsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/meetings'
    | '/edit/$id'
    | '/mom/$id'
    | '/mom/new'
    | '/api/public/moms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/meetings'
    | '/edit/$id'
    | '/mom/$id'
    | '/mom/new'
    | '/api/public/moms'
  id:
    | '__root__'
    | '/'
    | '/meetings'
    | '/edit/$id'
    | '/mom/$id'
    | '/mom/new'
    | '/api/public/moms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeetingsRoute: typeof MeetingsRoute
  EditIdRoute: typeof EditIdRoute
  MomIdRoute: typeof MomIdRoute
  MomNewRoute: typeof MomNewRoute
  ApiPublicMomsRoute: typeof ApiPublicMomsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$id': {
      id: '/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof EditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mom/$id': {
      id: '/mom/$id'
      path: '/mom/$id'
      fullPath: '/mom/$id'
      preLoaderRoute: typeof MomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mom/new': {
      id: '/mom/new'
      path: '/mom/new'
      fullPath: '/mom/new'
      preLoaderRoute: typeof MomNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/moms': {
      id: '/api/public/moms'
      path: '/api/public/moms'
      fullPath: '/api/public/moms'
      preLoaderRoute: typeof ApiPublicMomsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeetingsRoute: MeetingsRoute,
  EditIdRoute: EditIdRoute,
  MomIdRoute: MomIdRoute,
  MomNewRoute: MomNewRoute,
  ApiPublicMomsRoute: ApiPublicMomsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
