/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MomNewRouteImport } from './routes/mom.new'
import { Route as MomIdRouteImport } from './routes/mom.$id'
import { Route as MomIdEditRouteImport } from './routes/mom.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MomNewRoute = MomNewRouteImport.update({
  id: '/mom/new',
  path: '/mom/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MomIdRoute = MomIdRouteImport.update({
  id: '/mom/$id',
  path: '/mom/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MomIdEditRoute = MomIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MomIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mom/$id': typeof MomIdRouteWithChildren
  '/mom/new': typeof MomNewRoute
  '/mom/$id/edit': typeof MomIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mom/$id': typeof MomIdRouteWithChildren
  '/mom/new': typeof MomNewRoute
  '/mom/$id/edit': typeof MomIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mom/$id': typeof MomIdRouteWithChildren
  '/mom/new': typeof MomNewRoute
  '/mom/$id/edit': typeof MomIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mom/$id' | '/mom/new' | '/mom/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mom/$id' | '/mom/new' | '/mom/$id/edit'
  id: '__root__' | '/' | '/mom/$id' | '/mom/new' | '/mom/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MomIdRoute: typeof MomIdRouteWithChildren
  MomNewRoute: typeof MomNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mom/new': {
      id: '/mom/new'
      path: '/mom/new'
      fullPath: '/mom/new'
      preLoaderRoute: typeof MomNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mom/$id': {
      id: '/mom/$id'
      path: '/mom/$id'
      fullPath: '/mom/$id'
      preLoaderRoute: typeof MomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mom/$id/edit': {
      id: '/mom/$id/edit'
      path: '/edit'
      fullPath: '/mom/$id/edit'
      preLoaderRoute: typeof MomIdEditRouteImport
      parentRoute: typeof MomIdRoute
    }
  }
}

interface MomIdRouteChildren {
  MomIdEditRoute: typeof MomIdEditRoute
}

const MomIdRouteChildren: MomIdRouteChildren = {
  MomIdEditRoute: MomIdEditRoute,
}

const MomIdRouteWithChildren = MomIdRoute._addFileChildren(MomIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MomIdRoute: MomIdRouteWithChildren,
  MomNewRoute: MomNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
